<<<<<<< HEAD
# Generated by Django 4.2.2 on 2023-07-15 13:12
=======
# Generated by Django 4.2.2 on 2023-07-10 18:53
>>>>>>> 21e2b7d9825c6faf1af7217580d30cd3b5a4caaf

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("description", models.CharField(max_length=250)),
<<<<<<< HEAD
=======
                (
                    "price",
                    models.IntegerField(
                        validators=[api.product.models.validate_positive]
                    ),
                ),
                (
                    "stock",
                    models.IntegerField(
                        validators=[api.product.models.validate_positive]
                    ),
                ),
                ("is_active", models.BooleanField(blank=True, default=True)),
                ("image", models.ImageField(blank=True, upload_to="images/")),
>>>>>>> 21e2b7d9825c6faf1af7217580d30cd3b5a4caaf
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
