# Generated by Django 4.2.2 on 2023-07-06 03:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
