# Generated by Django 4.2.2 on 2023-07-14 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="create_at",
            new_name="created_at",
        ),
    ]
