
from rest_framework import routers
from django.urls import path, include
from . import views

#create an instance of default router
router = routers.DefaultRouter()
#register the viewset
router.register(r'', views.CategoryViewSet )

urlpatterns = [
# "" defines the root url include()  included the url generated by the router
    path("", include(router.urls))
]